.gitignore
puppetdb/client.go

This allows the user to override the default Transport
used by the HTTP client.
This is useful when using libraries such as go-vcr to inject
a fake transport.

(MAINT) Add Set Transport for PDB Client

---

puppetdb/reports.go
puppetdb/reports_test.go
puppetdb/testdata/reports.json

The report endpoint accepts the standard queries used by the API
i.e.
["=", "certname", "foobar.com"]

Add support for the reports endpoint

---

pkg/puppetdb/reports.go

This will allow users to query for the total number of reports using "reports ["extract", [["function", "count"] ]]"

(MAINT) Add a count field to reports struct

---

Makefile

The linter failed if no GOPATH was defined so define it when necessary.

Use default GOPATH if none is defined

---

pkg/orch/tasks.go
pkg/orch/tasks_test.go
pkg/orch/testdata/apidocs/task-response.json

The task metadata structs were specific to the "package" task and missed out a couple of other supported fields. This PR fixes up those problems.

Task metadata fixes

---

cmd/puppetdb/pdb.go
pkg/puppetdb/client.go
pkg/puppetdb/facts.go
pkg/puppetdb/facts_test.go
pkg/puppetdb/inventory.go
pkg/puppetdb/inventory_test.go
pkg/puppetdb/nodes.go
pkg/puppetdb/reports.go
pkg/puppetdb/reports_test.go

requests.
Users can now supply an optional OrderBy i.e.
```
&OrderBy{Field: "certname", Order: "asc"}
```
* refactor the nodes method to use the same getRequest as the other
API call.
* add count field to facts,reports and inventory to capture the response
when count() is used in a query.

Add the OrderBy clause to the reports, facts and inventory

---

pkg/puppetdb/client.go
pkg/puppetdb/pagination.go

If the user requests the include_total, then it will be
marshalled from the X-Records header into the pagnation object.

(MAINT) Return total if requested

---

cmd/main.go
pkg/puppetdb/client.go

Checks for a URL error and pulls out the underlying problem to clean up our errors. Also consistent error messaging for both HTTP errors and PuppetDB errors (like 404).

Unwrap URL errors after PuppetDB calls

---

Makefile

Run gosec (https://github.com/securego/gosec) as an additional lint step.
The build will not fail if problems are found though we should consider enabling that (same as lint) once we fix the existing issues.

Add gosec security checks to the build

---

Makefile
cmd/puppetdb/pdb.go
cmd/test/main.go
internal/cli/helpers.go
pkg/orch/client.go
pkg/orch/common_test.go
pkg/puppetdb/client.go
pkg/puppetdb/common_test.go

Replace NewInsecureClient with NewClient and force users to provide their own TLS config. That means the caller has responsibiity for deciding whether secure/insecure is the right approach in their context.
Move test main.go into its own subdir to make it clear its not related to the puppetdb cli tool.
Enable golint and fix up a few small lint errors.
Fix up remaining gosec issues and enable build failures if others are found in the future.
Fixes:
[/Users/scott/github/go-pe-client/cmd/puppetdb/pdb.go:132] - G307 (CWE-): Deferring unsafe method "*os.File" on type "Close" (Confidence: HIGH, Severity: MEDIUM)
> defer historyFile.Close()
[/Users/scott/github/go-pe-client/internal/cli/helpers.go:23] - G302 (CWE-276): Expect file permissions to be 0600 or less (Confidence: HIGH, Severity: …

(SEN-3868) Force user to specify TLS config plus other lint/security fixes

---

cmd/test/main.go
pkg/orch/plans.go
pkg/orch/plans_test.go
pkg/orch/testdata/apidocs/plan-response.json
pkg/orch/testdata/apidocs/plans-response.json

Adding support for plans in orchestrator as defined at https://puppet.com/docs/pe/latest/orchestrator_api_plans_endpoint.html

Add support for plans in orchestrator

---

pkg/orch/plans.go
pkg/orch/testdata/apidocs/plan-response.json
pkg/orch/testdata/apidocs/plans-response.json

Plan metadata is not always an empty object as the documentation suggests.

Changed type of plan metadata

---

cmd/test/main.go
pkg/classifier/client.go
pkg/classifier/groups.go
pkg/classifier/groups_test.go
pkg/classifier/pagination.go
pkg/classifier/testdata/group.json
pkg/classifier/testdata/groups-response.json

The classifier can be queried for all groups and for a specific group.
The group names are required for estate reporting filters.

Classifer Groups Query

---

pkg/classifier/client.go
pkg/classifier/rules.go

This adds the RuleTransform query, for converting the rule to a pdb
query.
See: https://puppet.com/docs/pe/2018.1/rules_endpoint.html for details

(MAINT) Add Rule Transform

---

cmd/puppetdb/pdb.go
cmd/test/main.go
pkg/puppetdb/client.go
pkg/puppetdb/common_test.go

Problem:
----------
An issue has occurred on estate reporting where an entire request times out if any PDB is unresponsive. 
Solution:
---------
Make it mandatory to pass a timeout to the PDB client on instantiation.
Testing:
--------
Tested with estate reporting with dial timeouts and timeouts when dial has worked but subsequently we are sending / receiving data. Both timeout at the configured time.

(LIDAR-338) Add timeout to PDB client.

---

cmd/test/main.go
pkg/pe/client.go
pkg/pe/common_test.go
pkg/pe/environments.go
pkg/pe/environments_test.go
pkg/pe/testdata/apidocs/environments.json

Add the root PE API i.e. https://mype.puppetlabs.net/api/...
Right now only environments are supported.

Initial support for PE root API

---

pkg/classifier/node.go

When node classifier executes request to API, the response is not checked for an error.
Additionally, the json.Unmarshal throws a panic unnecessarily instead of just returning
the error.

(CISC-849) Update node classifier error handling

---

pkg/puppetdb/facts.go
pkg/puppetdb/facts_test.go
pkg/puppetdb/testdata/factpaths-response.json

This changes the type of path from []string to []interface.
Valid Path values can be a slice of any JSON type e.g. both
these are valid:
```
{
"path" : [ "partitions", "sda3", "uuid" ],
"type" : "string"
}, {
"type" : "string",
"path" : ["apt_package_dist_updates",90]
}
```

(MAINT) Path should be []interface not []string

---

pkg/puppetdb/facts.go

FactPaths can return a count, so this adds the field to
the struct, so that the data can successfully be unmarshalled.

(MAINT) Add the count field to the factpaths type

---

pkg/orch/common_test.go
pkg/orch/jobs.go
pkg/orch/jobs_test.go

Problem:
----------
Compliance keeps it's own internal store of job ids. This has the potential to get out of sync with PE job store.
Solution:
----------
(Arguably there is a bigger solution). Send a specific error on return when the job is not found. This means that a caller can distinguish between errors when a job is not found.
Testing:
---------
- Added unit tests.
- Tested against a live PE and behaves as expected in unit tests etc.

(CISC-1061) Return a specific error when the job isn't found in PE.

---

pkg/orch/client.go
pkg/orch/command.go
pkg/orch/command_test.go
pkg/orch/common_test.go
pkg/orch/jobs.go
pkg/orch/jobs_test.go
pkg/orch/utils.go

Problem:
---------
When we have a HTTP error code then this should be able to be returned as part of the error from our APIs.
Solution:
----------
Extend current orchestrator error to add the status code and in the case of having a HTTP error but being unable to get an orchestrator error then return a http error. In the case where there is no http response just return a normal error (string).
Testing:
---------
Unit tests added.
(I still want to reproduce the non orchestrator error if possible so don't merge just yet)

(CISC-1167) Return error with HTTP status code.

---

pkg/orch/command.go
pkg/orch/command_test.go
pkg/orch/testdata/apidocs/command-deploy-request.json

When attempting to set enforce environment to false on the DeployRequest struct, it will always be excluded from the marshaled json due to the omitempty tag used. It appears to be true by default on PE.
However removing this omitempty tag means that when using the DeployRequest you must make sure to set enforce environment to true to get default behaviour.

(CISC-1277) Unable to set enforce_environment false

---

pkg/puppetdb/inventory.go

Adding ability to receive an Inventory message through a Map rather than Struct to allow for dot notation fields to be supported. The marshalling to Struct cannot support fields that could have many variants, it can only accept the top level fields.

(LIDAR-821) Dot notation support on Inventory message

---

pkg/puppetdb/common_test.go
pkg/puppetdb/status.go
pkg/puppetdb/status_test.go
pkg/puppetdb/testdata/puppetdbstatus-response.json

to address backward compatibility issue with the Query service group_by clauses -
a new endpoint has been added to the go-pe-client to call to return the version of the puppet db

(LIDAR-945) add new endpoint to return puppet db version

---

cmd/test/main.go
pkg/orch/command.go
pkg/orch/command_test.go

This will break existing code that uses the following:
* `orch.CommandTask`
* `orch.CommandScheduleTask`
... due to a change in the Params type in `TaskRequest` and `ScheduleTaskRequest` respectively.
As this breaks backwards compatibility, this may have to be a major release.
Fixes #59

fix: change params from string to interface{}

---

.travis.yml
cmd/test/main.go
go.mod
go.sum
pkg/classifier/groups_test.go
pkg/orch/common_test.go
pkg/pe/common_test.go
pkg/puppetdb/common_test.go
pkg/rbac/common_test.go
pkg/rbac/roles.go
pkg/rbac/roles_test.go
pkg/rbac/testdata/apidocs/GetRoles-response.json
pkg/rbac/token_test.go

**Resolves ticket:** [CISC-3188](https://tickets.puppetlabs.com/browse/CISC-3188)
**Summary of changes:**
* Added support for the PE RBAC API endpoint `GET /roles`
* Added an accompanying unit test and integration test
* Performed some minor opportunistic refactoring
* Bumped the Go version from 1.14 to 1.19
**Integration test output:**
```
% go run cmd/test/main.go oblique-heel.delivery.puppetlabs.net AKKwQ3aLRTgDWm_ysp8FVdXFMAyNDUTRFQT9kX1cqf9_
Connecting to: oblique-heel.delivery.puppetlabs.net
Create role "Testing 1680269553911422000" was successful, location: /rbac-api/v1/roles/6
Create role "Testing 1680269553911422000" failed as expected because role already exists
Get roles was successful, as role "Testing 1680269553911422000" was present in response
```

Add support for RBAC API get roles endpoint

---

cmd/test/main.go
pkg/rbac/roles.go
pkg/rbac/roles_test.go
pkg/rbac/testdata/apidocs/GetRole-response.json

**Resolves ticket:** [CISC-3191](https://tickets.puppetlabs.com/browse/CISC-3191)
**Summary of changes:**
* Added support for the PE RBAC API endpoint `GET /role/:id`
* Added an accompanying unit test and integration test
**Integration test output:**
```
% go run cmd/test/main.go epicyclical-pro.delivery.puppetlabs.net AL40f61YgFIhtIT_n1XBeWTbclTilG2r8NTSFX7ndHxP
Connecting to: epicyclical-pro.delivery.puppetlabs.net
* Testing RBAC API client function CreateRole...
Create role "Testing 1680519311359000000" was successful, location: /rbac-api/v1/roles/12
Create role "Testing 1680519311359000000" failed as expected because role already exists
* Testing RBAC API client function GetRole...
Get role was successful, as the role "Testing 1680519311359000000" was returned in response
* Testing …
```

Add support for RBAC API get role endpoint

---

pkg/puppetdb/facts.go
pkg/puppetdb/facts_test.go
pkg/puppetdb/nodes.go
pkg/puppetdb/pagination.go
pkg/puppetdb/testdata/facts-page-1-response.json
pkg/puppetdb/testdata/facts-page-2-response.json

This generalizes the pagination cursor a bit and makes it easier to wrap it with more constrained types for some endpoints. I also added a cursor for the facts endpoint since it's often used in conjunction with nodes.

pdb client: generalizes the pagination cursor

---

pkg/rbac/testdata/apidocs/AuthenticateRBACToken-request.json
pkg/rbac/testdata/apidocs/AuthenticateRBACToken-response.json
pkg/rbac/token.go
pkg/rbac/token_test.go

Problem:
We require to check whether a token is valid or not.
Solution:
Add the rbac v2 authenticate API.
Testing:
Tested with unit tests and tested with real PE.

(MAINT) Add token authenticate endpoint

---

pkg/rbac/client.go
pkg/rbac/common_test.go
pkg/rbac/token.go
pkg/rbac/token_test.go

Problem:
We have a need to use the revoke token API which PE doesn't have.
Solution:
Add the API as per docs https://www.puppet.com/docs/pe/2021.2/rbac_api_v2_tokens_endpoints#delete_tokens_lt_token_gt
Testing:
Unit testing added and code integrated with business logic and works as expected.

(MAINT) Add revoke token ability to RBAC APIs.

---

pkg/rbac/testdata/apidocs/GenerateToken-request.json
pkg/rbac/testdata/apidocs/GenerateToken-response.json
pkg/rbac/token.go
pkg/rbac/token_test.go

Problem:
The API to generate PE tokens from another token is something that could prove very useful in project Comply.
Solution:
Add the API as per PE docs.
Testing:
- Tested with unit tests.
- Included in local code and tested with a real PE. Works as expected.

(MAINT) Add the PE v1 /tokens endpoint

---

pkg/rbac/common_test.go
pkg/rbac/roles_test.go
pkg/rbac/testdata/apidocs/GetUser-response.json
pkg/rbac/testdata/apidocs/GetUsers-response.json
pkg/rbac/users.go
pkg/rbac/users_test.go

Problem:
We have a requirement to use the go-pe-client in order to query specific users, current users and all users.
Solution:
Provide an APi as per the PE docs.
Testing:
Unit testing performed.

Add PE users endpoints.
